#  ███████╗ ██████╗██╗  ██╗███████╗██████╗ ██╗   ██╗██╗     ██╗███████╗███████╗██████╗
#  ██╔════╝██╔════╝██║  ██║██╔════╝██╔══██╗██║   ██║██║     ██║╚══███╔╝██╔════╝██╔══██╗
#  ███████╗██║     ███████║█████╗  ██║  ██║██║   ██║██║     ██║  ███╔╝ █████╗  ██████╔╝
#  ╚════██║██║     ██╔══██║██╔══╝  ██║  ██║██║   ██║██║     ██║ ███╔╝  ██╔══╝  ██╔══██╗
#  ███████║╚██████╗██║  ██║███████╗██████╔╝╚██████╔╝███████╗██║███████╗███████╗██║  ██║
#  ╚══════╝ ╚═════╝╚═╝  ╚═╝╚══════╝╚═════╝  ╚═════╝ ╚══════╝╚═╝╚══════╝╚══════╝╚═╝  ╚═╝

# version: 1.0

# The number of ticks per scheduler run
#(20 ticks = 1 second, recommended 300 ticks = 15 seconds for performance and < 1200 ticks = 1 minute)
tick: 300

# https://www.timezoneconverter.com/cgi-bin/timezones
timezone: "Asia/Ho_Chi_Minh"

# dd/MM/yyyy HH:mm, yyyy-MM-dd HH:mm
datetime-format: "dd/MM/yyyy HH:mm"